[project]
name = "desmodus-server"
version = "0.1.0"
description = ""
authors = [
    {name = "JesuFrancesco",email = "117495071+JesuFrancesco@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi (==0.115.11)",
    "uvicorn (==0.34.0)",
    "annotated-types (==0.7.0)",
    "anyio (==4.8.0)",
    "certifi (==2025.1.31)",
    "cffi (==1.17.1)",
    "click (==8.1.8)",
    "colorama (==0.4.6)",
    "cryptography (==44.0.2)",
    "dnspython (==2.7.0)",
    "email-validator (==2.2.0)",
    "exceptiongroup (==1.2.2)",
    "faker (==37.1.0)",
    "fastapi-cli (==0.0.7)",
    "greenlet (==3.1.1)",
    "gunicorn (==23.0.0)",
    "h11 (==0.16.0)",
    "httpcore (==1.0.9)",
    "httptools (==0.6.4)",
    "httpx (==0.28.1)",
    "idna (==3.10)",
    "jinja2 (==3.1.6)",
    "markdown-it-py (==3.0.0)",
    "markupsafe (==3.0.2)",
    "mdurl (==0.1.2)",
    "packaging (==24.2)",
    "pillow (==11.1.0)",
    "psycopg2-binary (==2.9.10)",
    "pycparser (==2.22)",
    "pydantic (==2.10.6)",
    "pydantic-core (==2.27.2)",
    "pygments (==2.19.1)",
    "pyjwt (==2.10.1)",
    "pymysql (==1.1.1)",
    "python-dotenv (==1.0.1)",
    "python-multipart (==0.0.20)",
    "pyyaml (==6.0.2)",
    "rich (==13.9.4)",
    "rich-toolkit (==0.13.2)",
    "shellingham (==1.5.4)",
    "sniffio (==1.3.1)",
    "sqlalchemy (==2.0.39)",
    "sqlmodel (==0.0.24)",
    "starlette (==0.46.1)",
    "typer (==0.15.2)",
    "typing-extensions (==4.12.2)",
    "tzdata (==2025.2)",
    "uvicorn-worker (==0.3.0)",
    "uvloop (==0.21.0)",
    "watchfiles (==1.0.4)",
    "websockets (==15.0.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
