"""empty message

Revision ID: 4bf837d32b56
Revises: 5d099fd53f0e
Create Date: 2025-09-06 23:29:14.883920

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bf837d32b56"
down_revision: Union[str, None] = "5d099fd53f0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar_url",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    op.create_index(op.f("ix_users_avatar_url"), "users", ["avatar_url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_avatar_url"), table_name="users")
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
