"""empty message

Revision ID: 5d099fd53f0e
Revises:
Create Date: 2025-09-06 21:51:15.803689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5d099fd53f0e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archivos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_archivos_image_url"), "archivos", ["image_url"], unique=False
    )
    op.create_table(
        "departamentos",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("thumbnail_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departamentos_id"), "departamentos", ["id"], unique=False)
    op.create_table(
        "noticias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_noticias_content"), "noticias", ["content"], unique=False)
    op.create_index(op.f("ix_noticias_title"), "noticias", ["title"], unique=False)
    op.create_table(
        "noticia_archivos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("noticia_id", sa.Integer(), nullable=True),
        sa.Column("archivo_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["archivo_id"],
            ["archivos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["noticia_id"],
            ["noticias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provincias",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("departamento_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["departamento_id"],
            ["departamentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_provincias_id"), "provincias", ["id"], unique=False)
    op.create_table(
        "distritos",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("departamento_id", sa.String(), nullable=False),
        sa.Column("provincia_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["departamento_id"],
            ["departamentos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provincia_id"],
            ["provincias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_distritos_id"), "distritos", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dni", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("distrito_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["distrito_id"],
            ["distritos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_dni"), "users", ["dni"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=False)
    op.create_table(
        "avistamientos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("longitud", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("latitud", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("archivo_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("departamento_id", sa.String(), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archivo_id"],
            ["archivos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["departamento_id"],
            ["departamentos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("avistamientos")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_dni"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_distritos_id"), table_name="distritos")
    op.drop_table("distritos")
    op.drop_index(op.f("ix_provincias_id"), table_name="provincias")
    op.drop_table("provincias")
    op.drop_table("noticia_archivos")
    op.drop_index(op.f("ix_noticias_title"), table_name="noticias")
    op.drop_index(op.f("ix_noticias_content"), table_name="noticias")
    op.drop_table("noticias")
    op.drop_index(op.f("ix_departamentos_id"), table_name="departamentos")
    op.drop_table("departamentos")
    op.drop_index(op.f("ix_archivos_image_url"), table_name="archivos")
    op.drop_table("archivos")
    # ### end Alembic commands ###
