"""empty message

Revision ID: a094d9bd3ab6
Revises: 4bf837d32b56
Create Date: 2025-10-19 16:18:06.922387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a094d9bd3ab6"
down_revision: Union[str, None] = "4bf837d32b56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "avistamientos",
        sa.Column("x", sa.DECIMAL(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        "avistamientos",
        sa.Column("y", sa.DECIMAL(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        "avistamientos",
        sa.Column("w", sa.DECIMAL(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        "avistamientos",
        sa.Column("h", sa.DECIMAL(precision=10, scale=4), nullable=True),
    )
    op.alter_column(
        "avistamientos",
        "longitud",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.DECIMAL(precision=10, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "avistamientos",
        "latitud",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.DECIMAL(precision=10, scale=4),
        existing_nullable=True,
    )
    op.add_column(
        "users",
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "users", sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("centro_poblado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("users", "dni", existing_type=sa.VARCHAR(length=8), nullable=True)
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users",
        "avatar_url",
        existing_type=sa.VARCHAR(),
        server_default=None,
        nullable=True,
    )
    op.create_index(op.f("ix_users_address"), "users", ["address"], unique=False)
    op.create_index(
        op.f("ix_users_centro_poblado"), "users", ["centro_poblado"], unique=False
    )
    op.create_index(
        op.f("ix_users_document_type"), "users", ["document_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_document_type"), table_name="users")
    op.drop_index(op.f("ix_users_centro_poblado"), table_name="users")
    op.drop_index(op.f("ix_users_address"), table_name="users")
    op.alter_column(
        "users",
        "avatar_url",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("''::character varying"),
        nullable=False,
    )
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "dni", existing_type=sa.VARCHAR(length=8), nullable=False)
    op.drop_column("users", "centro_poblado")
    op.drop_column("users", "address")
    op.drop_column("users", "document_type")
    op.alter_column(
        "avistamientos",
        "latitud",
        existing_type=sa.DECIMAL(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "avistamientos",
        "longitud",
        existing_type=sa.DECIMAL(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.drop_column("avistamientos", "h")
    op.drop_column("avistamientos", "w")
    op.drop_column("avistamientos", "y")
    op.drop_column("avistamientos", "x")
    # ### end Alembic commands ###
