name: FastAPI CI

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]

jobs:
  build-and-release:
    name: Build & Deploy to Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            server

      - name: Instalar python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Instalar las dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pruebas unitarias
        run: |
          echo "wip"
