name: Supabase heartbeat
run-name: Supabase heartbeat - ${{ github.ref_name }}

on:
  schedule:
    - cron: "0 17 * * *"

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

defaults:
  run:
    working-directory: packages/supabase-heartbeat

jobs:
  supabase-heartbeat-job:
    name: Supabase heartbeat job
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código fuente (sparse-checkout a /jobs)
        uses: actions/checkout@v4
        with:
          sparse-checkout: packages/supabase-heartbeat

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: packages/supabase-heartbeat/pnpm-lock.yaml

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar script
        run: pnpm run execute
